#!/usr/bin/env ruby

require 'rspec/multiprocess_runner/command_line_options'
require 'rspec/multiprocess_runner/coordinator'

options = RSpec::MultiprocessRunner::CommandLineOptions.new.parse(ARGV.dup)
exit(2) unless options

coordinator = RSpec::MultiprocessRunner::Coordinator.new(
  options.worker_count,
  options.files_to_run,
  {
    file_timeout_seconds: options.file_timeout_seconds,
    example_timeout_seconds: options.example_timeout_seconds,
    test_env_number_first_is_1: options.first_is_1,
    rspec_options: options.rspec_options,
    log_failing_files: options.log_failing_files
  }
)

trap("INT") do
  $stderr.puts "INT happened"
  coordinator.shutdown(print_summary: true)
  Kernel.exit(4)
end

trap("TERM") do
  coordinator.shutdown
  Kernel.exit(3)
end

success = coordinator.run

exit(success ? 0 : 1)
