#!/usr/bin/env ruby

require 'rspec/multiprocess_runner/command_line_options'
require 'rspec/multiprocess_runner/coordinator'

options = RSpec::MultiprocessRunner::CommandLineOptions.new.parse(ARGV.dup)
exit(2) unless options

success = RSpec::MultiprocessRunner::Coordinator.new(
  options.worker_count,
  options.files_to_run,
  {
    file_timeout_seconds: options.file_timeout_seconds,
    rspec_options: options.rspec_options
  }
).run

exit(success ? 0 : 1)
