#!/usr/bin/env ruby

require 'rspec/multiprocess_runner/coordinator'

process_count = ARGV[0].to_i
fail "Invalid process count #{ARGV[0]}" if process_count < 1

spec_files = ARGV[1..-1].flat_map do |filename|
  if File.directory?(filename)
    Dir["#{filename}/**/*_spec.rb"]
  else
    filename
  end
end

success = RSpec::MultiprocessRunner::Coordinator.new(process_count, 300, [], spec_files).run

exit(success ? 0 : 1)
